name: EVE Trade
version: v6.5
version_full: Version 6.5
baseurl:
url: https://evetrade.space

destination: dist

exclude:
    - README.md
    - netlify.toml
    - CNAME
    - LICENSE
    - Gemfile
    - .gitignore
    - .github

plugins:
    - jekyll-minifier

jekyll-minifier:
  exclude:
    - release.html
    - sitemap.xml
